/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    clients: Client;
    vehicles: Vehicle;
    services: Service;
    'part-purchases': PartPurchase;
    tools: Tool;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    vehicles: VehiclesSelect<false> | VehiclesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'part-purchases': PartPurchasesSelect<false> | PartPurchasesSelect<true>;
    tools: ToolsSelect<false> | ToolsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  ime: string;
  uloga: 'vlasnik' | 'mehanicar' | 'pomocni';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  firstName: string;
  lastName?: string | null;
  phone: string;
  email?: string | null;
  address?: string | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles".
 */
export interface Vehicle {
  id: number;
  client: number | Client;
  brand?: string | null;
  model: string;
  year?: number | null;
  registrationNumber?: string | null;
  vin: string;
  engine?: string | null;
  fuelType?: string | null;
  engineCapacity?: string | null;
  power?: string | null;
  color?: string | null;
  currentMileage?: number | null;
  note?: string | null;
  gallery?:
    | {
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  tip?: ('slika-vozila' | 'slika-kvara' | 'racun' | 'ostalo') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  vehicle: number | Vehicle;
  client?: (number | null) | Client;
  clientSnapshotName?: string | null;
  serviceType: 'mali-servis' | 'veliki-servis' | 'popravka-kvara' | 'dijagnostika' | 'limarija-ostalo';
  serviceDate: string;
  mileage: number;
  description: string;
  partsUsed?:
    | {
        partName?: string | null;
        brand?: string | null;
        partCode?: string | null;
        quantity?: number | null;
        purchasePrice?: number | null;
        salePrice?: number | null;
        supplier?: string | null;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  laborPrice?: number | null;
  partsPrice?: number | null;
  totalPrice?: number | null;
  paymentStatus?: ('placeno' | 'nije-placeno' | 'delimisno-placeno') | null;
  paymentMethod?: ('gotovina' | 'kartica' | 'virman') | null;
  partsInvoiceFiles?:
    | {
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  issueImages?:
    | {
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  afterRepairImages?:
    | {
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  internalNote?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "part-purchases".
 */
export interface PartPurchase {
  id: number;
  purchaseDate?: string | null;
  supplier?: string | null;
  invoiceNumber?: string | null;
  totalAmount?: number | null;
  invoiceFiles?:
    | {
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  items?:
    | {
        name?: string | null;
        code?: string | null;
        quantity?: number | null;
        unitPrice?: number | null;
        total?: number | null;
        id?: string | null;
      }[]
    | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools".
 */
export interface Tool {
  id: number;
  name: string;
  category?: string | null;
  description?: string | null;
  serialNumber?: string | null;
  purchaseDate?: string | null;
  purchasePrice?: number | null;
  locationInWorkshop?: string | null;
  condition?: ('ispravno' | 'na-servisu' | 'neispravno' | 'rashodovano') | null;
  images?:
    | {
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'vehicles';
        value: number | Vehicle;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'part-purchases';
        value: number | PartPurchase;
      } | null)
    | ({
        relationTo: 'tools';
        value: number | Tool;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  ime?: T;
  uloga?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?: T;
  email?: T;
  address?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vehicles_select".
 */
export interface VehiclesSelect<T extends boolean = true> {
  client?: T;
  brand?: T;
  model?: T;
  year?: T;
  registrationNumber?: T;
  vin?: T;
  engine?: T;
  fuelType?: T;
  engineCapacity?: T;
  power?: T;
  color?: T;
  currentMileage?: T;
  note?: T;
  gallery?:
    | T
    | {
        file?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  vehicle?: T;
  client?: T;
  clientSnapshotName?: T;
  serviceType?: T;
  serviceDate?: T;
  mileage?: T;
  description?: T;
  partsUsed?:
    | T
    | {
        partName?: T;
        brand?: T;
        partCode?: T;
        quantity?: T;
        purchasePrice?: T;
        salePrice?: T;
        supplier?: T;
        note?: T;
        id?: T;
      };
  laborPrice?: T;
  partsPrice?: T;
  totalPrice?: T;
  paymentStatus?: T;
  paymentMethod?: T;
  partsInvoiceFiles?:
    | T
    | {
        file?: T;
        id?: T;
      };
  issueImages?:
    | T
    | {
        file?: T;
        id?: T;
      };
  afterRepairImages?:
    | T
    | {
        file?: T;
        id?: T;
      };
  internalNote?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "part-purchases_select".
 */
export interface PartPurchasesSelect<T extends boolean = true> {
  purchaseDate?: T;
  supplier?: T;
  invoiceNumber?: T;
  totalAmount?: T;
  invoiceFiles?:
    | T
    | {
        file?: T;
        id?: T;
      };
  items?:
    | T
    | {
        name?: T;
        code?: T;
        quantity?: T;
        unitPrice?: T;
        total?: T;
        id?: T;
      };
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tools_select".
 */
export interface ToolsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  description?: T;
  serialNumber?: T;
  purchaseDate?: T;
  purchasePrice?: T;
  locationInWorkshop?: T;
  condition?: T;
  images?:
    | T
    | {
        file?: T;
        id?: T;
      };
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  tip?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}